# Generated by Django 3.0.1 on 2020-01-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='brandname',
        ),
    ]
