# Generated by Django 3.0.1 on 2019-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='username',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
