# Generated by Django 3.0.1 on 2020-01-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200117_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_name',
            field=models.CharField(choices=[(1, 'CSE'), (2, 'ECE'), (3, 'ECE'), (4, 'MECHANICAL'), (5, 'MECHATRONICS'), (6, 'Applied')], default='CSE', max_length=250),
        ),
    ]
