# Generated by Django 3.0.1 on 2020-01-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200117_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_name',
            field=models.CharField(choices=[('1', 'CSE'), ('ECE', 'ECE'), ('ECE', 'ECE'), ('MECHANICAL', 'MECHANICAL'), ('MECHATRONICS', 'MECHATRONICS'), ('Applied', 'Applied')], default='CSE', max_length=250),
        ),
    ]
