# Generated by Django 3.0.1 on 2020-01-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dept2',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app1.Dept'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='dept_name',
            field=models.CharField(choices=[('1', 'CSE'), ('ECE', 'ECE'), ('ECE', 'ECE'), ('MECHANICAL', 'MECHANICAL'), ('MECHATRONICS', 'MECHATRONICS'), ('Applied', 'Applied')], default='1', max_length=250),
        ),
    ]
