# Generated by Django 3.0.1 on 2020-01-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200117_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_name',
            field=models.CharField(max_length=250),
        ),
    ]
